
[prompt]
name = "copy_file"
description = "Copy a file from one GCS bucket to another."
content = """
I want to copy a file from one GCS bucket to another.

Please ask me for the following information:
- The source bucket name.
- The source blob name.
- The destination bucket name.
- The destination blob name.

Once you have this information, please run the following command:
{{#tool}}copy_blob(source_bucket_name=<source_bucket_name>, blob_name=<blob_name>, destination_bucket_name=<destination_bucket_name>, destination_blob_name=<destination_blob_name>){{/tool}}
"""
