
[prompt]
name = "delete_bucket"
description = "Delete a GCS bucket."
content = """
I want to delete a GCS bucket.

Please ask me for the name of the bucket to delete.

Once you have the bucket name, please run the following command:
{{#tool}}delete_bucket(bucket_name=<bucket_name>){{/tool}}
"""
